// Code generated by mockery v1.0.0. DO NOT EDIT.

// Regenerate this file using `make store-mocks`.

package mocks

import mock "github.com/stretchr/testify/mock"

// ExtRefStore is an autogenerated mock type for the ExtRefStore type
type ExtRefStore struct {
	mock.Mock
}
