// Code generated by mockery v1.0.0. DO NOT EDIT.

// Regenerate this file using `make store-mocks`.

package mocks

import (
	model "github.com/mattermost/mattermost-server/v5/model"
	mock "github.com/stretchr/testify/mock"
)

// SecretStore is an autogenerated mock type for the SecretStore type
type SecretStore struct {
	mock.Mock
}

// GetBySecretName provides a mock function with given fields: secretName
func (_m *SecretStore) GetBySecretName(secretName string) (*model.Secret, error) {
	ret := _m.Called(secretName)

	var r0 *model.Secret
	if rf, ok := ret.Get(0).(func(string) *model.Secret); ok {
		r0 = rf(secretName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Secret)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(secretName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
